### ISSUE TITLE
Server Status message not initialized/sent

### ISSUE THREAD

**Issue by weeestar** [NockyCZ/CS2-Discord-Utilities#12]
I cannot get the server status message initialized. I've tried to recreate a new bot, a new channel, a new public channel in case it was permissions issue... but still dont work. Anything else enabled is working properly: rcon, link, roles and permissions.

I've attempted to update the plugin with the last release, but still not working. I've read, re-read, re-re-read the documentation in case I forgot something but...

---

My server status config:
```
"Server Status Section": {
        "Update Time": 1800,
        "Channel ID": "1224330886049435710",
        "Message ID": "",
        "Server Status Embed": {
            "Content": "",
            "Title": "{Server.Name}",
            "Description": "\u003E IP: \u0060{Server.IP}\u0060\n\u003E",
            "Fields": "\uD83D\uDC65 Joueurs;{Server.OnlinePlayersAndBots}/{Server.MaxPlayers};True|\uD83D\uDDFA\uFE0F Map;{Server.MapName};True",
            "Thumbnail": "",
            "Image": "https://i.postimg.cc/brW3DJDp/Dust-2-CS2-1.jpg",
            "HEX Color": "#ffad33",
            "Footer": "Dernière mise à jour",
            "Footer Timestamp": true,
            "First Embed Component": 1,
            "Join Button": {
                "Enabled": false,
                "Button Text": "Rejoindre maintenant",
                "Button URL": "steam://connect/89.116.110.160:27015/",
                "Button Emoji": ""
            },
            "Players Menu": {
                "Enabled": false,
                "Menu Name": "Liste des Joueurs",
                "Players Format": "{Player.Name} | {Player.Kills}/{Player.Deaths}",
                "On Click On Player in Menu Embed": {
                    "Content": "",
                    "Title": "{Player.Name}",
                    "Description": "{Player.DiscordPing} Ce joueur est **{Player.TeamLongName}**",
                    "Fields": "Kills;{Player.Kills};true|Deaths;{Player.Deaths};true|Assists;{Player.Assists};true",
                    "Thumbnail": "",
                    "Image": "",
                    "HEX Color": "#39e600",
                    "Footer": "",
                    "Footer Timestamp": false
                }
            }
        }
    },
```

Discord role settings:

<img width="1018" alt="Captura de ecrã 2024-04-01, às 14 23 23" src="https://github.com/NockyCZ/CS2-Discord-Utilities/assets/162443646/c2c84511-2ea8-4ee0-9479-bb10f264ab36">

<img width="1018" alt="Captura de ecrã 2024-04-01, às 14 23 40" src="https://github.com/NockyCZ/CS2-Discord-Utilities/assets/162443646/2183a701-fb08-4790-a1ef-b0dd3c4a7c76">

<img width="1018" alt="Captura de ecrã 2024-04-01, às 14 23 49" src="https://github.com/NockyCZ/CS2-Discord-Utilities/assets/162443646/4392d75b-6cf6-4343-9818-f2fd01b7943c">

--- 

Then I run `css_du_serverstatus` and nothing happens. If I use a fake channel ID, I get the "incorrect channel ID"-like message, so for me, it means that it tried to send the message.

**Comment by NockyCZ** [comment]
Fixed -> https://github.com/NockyCZ/CS2-Discord-Utilities/releases/tag/v1.0.9
