### ISSUE TITLE
[Feature] Hostname Suffix scraping for variable

### ISSUE THREAD

**Issue by mavproductions** [NockyCZ/CS2-Discord-Utilities#16]
Hey Nocky, 

Would you be open to adding a variable for scraping a concatenated/delimited suffix?

Example: `hostname "hostnameHere" - <concatenated info here>` 

The idea is that a server operator can have configs ran on mode changes (retakes/surf/etc) and in the discord activity status, people can monitor what mode the server is currently on along with a new {HostnameSuffix} variable other available variables (current players, etc)

Thanks for considering.

Cheers,

**Comment by NockyCZ** [comment]
in the future i plan to add custom variables with conditions

**Comment by mavproductions** [comment]
Okay sweet! Thanks

**Comment by NockyCZ** [comment]
Added - https://github.com/NockyCZ/CS2-Discord-Utilities/releases/tag/v2.0.3
