### ISSUE TITLE
IP bug

### ISSUE THREAD

**Issue by tungsten35** [NockyCZ/CS2-Discord-Utilities#21]
I set my IP but it is still IP: 0.0.0.0:27015 on Discord Server Status

**Comment by Kanetrix** [comment]
for me too...

**Comment by tungsten35** [comment]
Just delete config and download latest release from zero. I fixed it this way because they changed config so newest config fixed the issue.

**Comment by NockyCZ** [comment]
Yeah, the config has been changed, so a new one needs to be generated

**Comment by Kanetrix** [comment]
thank you now it works

ut 28. 5. 2024 o 22:47 Nocky ***@***.***> napísal(a):
