### ISSUE TITLE
Server status problem

### ISSUE THREAD

**Issue by tungsten35** [NockyCZ/CS2-Discord-Utilities#23]
---> System.InvalidOperationException: The url steam://connect/185.171.25.17:27015 must include a protocol (either HTTP, HTTPS, or DISCORD)

Invalid Button URL, you need to use https://example.com/

You said this but is there a way to make it work "steam://connect/185.171.25.17:27015" this?

**Comment by NockyCZ** [comment]
Create an http website that redirects you to steam://xxxx

**Comment by Armageddon87270** [comment]
Hi,
Put this https://connectsteam.me/?185.171.25.17:27015
