### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by KernalCorn** [NockyCZ/CS2-Discord-Utilities#28]
EDIT 
So i got the discord bot set up and added to my discord server. 
I have set up the cfg/plugin/discordutil/.JSON file with my DB / server / etc... 
Is there anything else i need to customize? 

On discord, after adding the bot and ensuring he has admin, what else do i do? he does not post anything... lol 

Thanks!

**Comment by NockyCZ** [comment]
and what should he post?

**Comment by NockyCZ** [comment]
There is always a description for each property in the documentation
