### ISSUE TITLE
BOT

### ISSUE THREAD

**Issue by rasinski** [NockyCZ/CS2-Discord-Utilities#29]
After restarting my server and editing the config for the bot token, discord id, server ip and database I'm just getting "Discord BOT is not connected!". The database connected but the bot doesn't seem to want to.
Any help would be appreciated

**Comment by NockyCZ** [comment]
https://docs.sourcefactory.eu/cs2-plugins/discord-utilities/setting-up-a-discord-bot Here you can check how to set up discord bot

**Comment by rasinski** [comment]
I’ve tried that a few times. Followed the steps, invited to the discord. Ill go through the process again i must have missed something i guess

**Comment by rasinski** [comment]
Figured it out on another server that i was testing and it worked perfectly . So must be something on the other that is causing the problem

**Comment by NockyCZ** [comment]
well, you must have something wrong on the other server :D
