### ISSUE TITLE
[v2.0.7] Performance Issues

### ISSUE THREAD

**Issue by mstankov** [NockyCZ/CS2-Discord-Utilities#31]
Hi, first of all thanks for the great plugin set.

Yesterday I updated to the latest v2.0.7 and started seeing some serious performance issues on the server. I'm not sure that the update is responsible but I wanted to check if I'm the only one.

I'm using the `ChatRelay`, `EventNotifications`, `Report` and `ServerStatus`. From the new features, I'm using the map leaderboard functionality at the end of the map, along with player connect/disconnect and map change.

I can't dig in right now and check what exactly's happening with the events but do you think any of the recent changes can cause performance issues compared to the previous versions?

Regards

**Comment by NockyCZ** [comment]
I don't think it's caused by DU, no changes have been made that will affect the peformence server, but rather improve it.
When i have some free time, I'll check if it's on my server too

**Comment by mstankov** [comment]
Yep, can confirm. Did some testing with the different modules and it's definitely not a DU issue
