### ISSUE TITLE
[REQ] Option to configure redirection and map image links

### ISSUE THREAD

**Issue by crashzk** [NockyCZ/CS2-Discord-Utilities#45]
Would it be possible to support configuring the redirection link and map image?

https://github.com/NockyCZ/CS2-Discord-Utilities/blob/bf5fb69b1dd91f2339d4f15d756a55d16fdff906/src/DiscordUtilities/Functions/Helpers.cs#L418-L419

If so, I would like to switch to another link.

**Comment by NockyCZ** [comment]
You don't have to use those variables, just use your own link instead of that variable

**Comment by crashzk** [comment]
Map image I configured like this:
```
"Image": "https://github.com/ghostcap-gaming/cs2-map-images/tree/main/cs2/{mapName}.png",
```
But without success, it does not display the map image.

**Comment by NockyCZ** [comment]
{Server.MapName}
