### ISSUE TITLE
I don't understand add role

### ISSUE THREAD

**Issue by Truyn** [NockyCZ/CS2-Discord-Utilities#6]
I gave the rights to the bot, the account was added to the database, but I did not receive the role.

**Comment by NockyCZ** [comment]
The bot will give a role after reconnect. In the next update it will add it immediately. And also i can try fix DB duplicate

**Comment by Truyn** [comment]
> The bot will give a role after reconnect. In the next update it will add it immediately. And also i can try fix DB duplicate

You are mistaken, nothing is displayed after reconnect

**Comment by NockyCZ** [comment]
and what should be displayed?

**Comment by NockyCZ** [comment]
Fixed > https://github.com/NockyCZ/CS2-Discord-Utilities/releases/tag/v1.0.4
