### ISSUE TITLE
chat logs

### ISSUE THREAD

**Issue by szogun1910** [NockyCZ/CS2-Discord-Utilities#7]
Hey is it possible to add something like silent so that e.g. a message is not sent in the logs when we write e.g. !ws etc.

**Comment by szogun1910** [comment]
@NockyCZ

**Comment by NockyCZ** [comment]
Yeah, i will add it

**Comment by szogun1910** [comment]
One more thing when someone has emoticons in their nickname on discord it looks like this
![Uploading Screenshot_2024-03-15-18-20-47-678_com.discord.jpg…]()

**Comment by NockyCZ** [comment]
> One more thing when someone has emoticons in their nickname on discord it looks like this
> 
> {Player.CountryEmoji} **[{Player.NameWithoutEmoji}](%7BPlayer.CommunityUrl%7D)**: !7

And if a player doesn't have emoticons in their name, is that correct?

**Comment by szogun1910** [comment]
If it doesn't have emoticons in the name it works fine
