### ISSUE TITLE
Add RCon

### ISSUE THREAD

**Issue by 4fc7c8f789** [NockyCZ/CS2-Discord-Utilities#9]
Thanks a lot for developing this! Any plans to add RCon functionality to the tool?

That would turn the discord channel / this plugin into a full admin control room :)

I've seen it done here: https://github.com/imi-tat0r/CS2-DiscordChatSync?tab=readme-ov-file

But that plugin in is missing server status and other important functionalities...

**Comment by NockyCZ** [comment]
Added - https://github.com/NockyCZ/CS2-Discord-Utilities/releases/tag/v1.0.6
